name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'file:./dev.db'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
        continue-on-error: false
      - name: Test
        run: npm run test
        continue-on-error: false
      - name: Build
        run: npm run build
        continue-on-error: false
